config/routes.rb
Rails.application.routes.draw do
  
  root                              "top_pages#home"
  get    "/signup",             to: "users#new"
  post   "/signup",             to: "users#create"
  get    "/login",              to: "sessions#new"
  post   "/login",              to: "sessions#create"
  delete "/logout",             to: "sessions#destroy"
  
  resources :users, shallow: true, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
    resources :posts,         only: [:show, :new, :create, :destroy] do
      resources :comments,    only: [:create, :destroy]
    end
  end

  resources :password_resets, only: [:edit, :update]
  resources :relationships,   only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy                                
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :image, ImageUploader
  validates :name,     presence: true, length: {maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/                  
  validates :tel,      format: { with: VALID_PHONE_REGEX }, allow_blank: true
  validates :username, presence: true, length: { maximum: 10 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  enum sex: { 未選択: 0, 男性: 1, 女性: 2 }
  validate :image_size
  
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})OR user_id = :user_id", user_id: id)
  end
  
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  private
  
   # アップロードされた画像のサイズをバリデーションする
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "投稿できるサイズは5MB以下です。")
      end
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "アカウントを作成しました!"
      redirect_to root_url
    else
      flash.now[:danger] = "無効な入力です。"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.paginate(page: params[:page], per_page: 12)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(edit_params)
      flash[:success] = "プロフィールが保存されました。"
      redirect_to edit_user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "ユーザーを削除しました"
      redirect_to root_url
    else
      flash[:danger] = "ユーザーが見つかりません"
      redirect_to root_url
    end
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follower'
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :password)
    end
    
    def edit_params
      params.require(:user).permit(:image, :name, :username, :website, :introduce, :email, :sex)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_current_user_show.html.erb
<% provide(:title, "マイページ") %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-xs-5 col-sm-5 col-md-5">
            <div class="profile-image">
              <% if current_user.image.blank? %>
                <%= image_tag("default.jpg", alt: "default_image", class: "img-responsive") %>
              <% else%>
                <%= image_tag(current_user.image, class: "img-responsive") %>
              <% end %>  
            </div>
          </div>
          <div class="col-xs-7 col-sm-7 col-md-7 profile-box">
            <h1><%= current_user.username %></h1>
            <%= link_to "プロフィールを編集", edit_user_path(current_user), class: "btn btn-light" %>
            <%= link_to "ログアウト", logout_path, class: "btn btn-light", method: :delete, data: { confirm: "ログアウトしますか？" } %>
            <p>
              <%= "投稿#{current_user.posts.count}件" %>
              <a href="<%= following_user_path(current_user) %>">
                <strong id="following" class="stat">
                  <%= current_user.following.count %>
                </strong>
                人をフォロー中
              </a>
              <a href="<%= followers_user_path(current_user) %>">
                フォロワー
                <strong id="followers" class="stat">
                  <%= current_user.followers.count %>
                </strong>
                人
              </a>
            </p>  
            <%= current_user.introduce %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_other_user_show.html.erb
  <% provide(:title, @user.name ) %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-xs-5 col-sm-5 col-md-5">
            <div class="profile-image">
              <% if @user.image.blank? %>
                <%= image_tag("default.jpg", alt: "default_image", class: "img-responsive") %>
              <% else%>
                <%= image_tag(@user.image, class: "img-responsive") %>
              <% end %>  
            </div>
          </div>
          <div class="col-xs-7 col-sm-7 col-md-7">
            <h1><%= @user.username %></h1>
            <% if logged_in? %>
            <div id="follow_form">
              <% if current_user.following?(@user) %>
                <%= render 'unfollow' %>
              <% else %>
                <%= render 'follow' %>
              <% end %>
            </div>
            <% end %>
            <p>
              <%= "投稿#{@user.posts.count}件" %>
              <a href="<%= following_user_path(@user) %>">
                <strong id="following" class="stat">
                  <%= @user.following.count %>
                </strong>
                人をフォロー中
              </a>
              <a href="<%= followers_user_path(@user) %>">
                フォロワー
                <strong id="followers" class="stat">
                  <%= @user.followers.count %>
                </strong>
                人
              </a>
            </p>  
            <%= @user.introduce %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, data: { confirm: "#{@user.name}さんのフォローをやめますか？" }) do |f| %>
  <%= f.submit "フォロー中", class: "btn" %>
<% end %>

app/views/users/_user_posts.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 posts-area">
      <%= will_paginate @post %>
      <div class="row">
        <% @post.each do |post| %>
          <div class="col-xs-4 posts-box">
            <%= link_to image_tag(post.image, class: "img-responsive", size: 13*13), post_path(post) %>
          </div>
        <% end %>
      </div>
      <%= will_paginate @post %>
    </div>  
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集ページ") %>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="box-edit">
        <%= form_for(@user, url: user_path ) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <h1>Edit Profile</h1>
          <div class="image-control">
            <% if current_user.image.blank? %>
              <%= image_tag("default.jpg", alt: "default_image", size: 8*8) %>
            <% else %>
              <%= image_tag(current_user.image, size: 8*8) %>
            <% end %>
            <%= f.label :image, "プロフィール画像を変更"%>
          </div>
          <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "file_select" %>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="form-group row">
                <div class="col-xs-4">
                  <%= f.label :name, "フルネーム" %>
                </div>
                <div class="col-xs-8">
                  <%= f.text_field :name, placeholder: "フルネーム", class: 'form-control' %>
                </div>  
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="form-group row">
                <div class="col-xs-4">
                  <%= f.label :username, "ユーザーネーム" %>
                </div>
                <div class="col-xs-8">
                  <%=f.text_field :username, placeholder: "ユーザーネーム", class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="form-group row">
                <div class="col-xs-4">
                  <%= f.label :website, "ウェブサイト" %>
                </div>
                <div class="col-xs-8">
                  <%= f.text_field :website, placeholder: "URL", class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="form-group row">
                <div class="col-xs-4">
                  <%= f.label :introduce, "自己紹介" %>
                </div>
                <div class="col-xs-8">
                  <%= f.text_area :introduce, placeholder: "自己紹介", class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
          <p>非公開情報</p>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="form-group row">
                <div class="col-xs-4">
                  <%= f.label :email, "メールアドレス" %>
                </div>
                <div class="col-xs-8">
                  <%= f.email_field :email, placeholder: "メールアドレス", class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="form-group row">
                <div class="col-xs-4">
                  <%= f.label :sex, "性別" %>
                </div>
                <div class="col-xs-8">
                  <%= f.select :sex, ["未選択", "男性","女性"], placeholder: "性別", class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
          <p><%= f.submit "送信する", class: "btn btn-primary" %></p>
        <% end %>
        <%= link_to "パスワード再設定", edit_password_reset_path(@user), class: "btn btn-primary" %>
        <%= link_to "ログアウト", logout_path, class: "btn btn-primary", method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="box">
      <h1>Rastagram</h1>
      <%= render 'shared/form' %>
      <p><%= link_to "利用規約", "#" %></p>
    </div>
  </div>  
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
  <%= render "users/current_user_show" %>
<% else %>
  <%= render "users/other_user_show" %>
<% end %>
<%= render "users/user_posts" %>

app/views/users/show_follow.html.erb
<% provide(:title, "フォロー中のユーザー") %>
<h1 class="text-center">フォロー中のユーザー</h1>
<%= will_paginate %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
      <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-5">
          <% @user.following.each do |user_following| %>
          <div class="profile-image">
            <% if user_following.image.blank? %>
              <%= link_to image_tag("default.jpg", alt: "default_image", class: "img-responsive"), user_path(user_following) %>
            <% else%>
              <%= link_to image_tag(user_following.image, class: "img-responsive"), user_path(user_following) %>
            <% end %>  
          </div>
        </div>
        <div class="col-xs-7 col-sm-7 col-md-7 profile-box">
          <h1><%= link_to user_following.username, user_path(user_following) %></h1>
          <p>
            <%= link_to "投稿#{user_following.posts.count}件", user_path(user_following) %>
            <a href="<%= following_user_path(user_following) %>">
              <strong id="following" class="stat">
                <%= user_following.following.count %>
              </strong>
              人をフォロー中
            </a>
            <a href="<%= followers_user_path(user_following) %>">
              フォロワー
              <strong id="followers" class="stat">
                <%= user_following.followers.count %>
              </strong>
              人
            </a>
          </p>  
          <%= user_following.introduce %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= will_paginate %>

app/views/users/show_follower.html.erb
<% provide(:title, "フォロワー") %>
<h1 class="text-center">フォロワー</h1>
<%= will_paginate %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
      <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-5">
          <% @user.followers.each do |user| %>
          <div class="profile-image">
            <% if user.image.blank? %>
              <%= link_to image_tag("default.jpg", alt: "default_image", class: "img-responsive"), user_path(user) %>
            <% else%>
              <%= link_to image_tag(user.image, class: "img-responsive"), user_path(user) %>
            <% end %>  
          </div>
        </div>
        <div class="col-xs-7 col-sm-7 col-md-7 profile-box">
          <h1><%= link_to user.username, user_path(user) %></h1>
          <p>
            <%= link_to "投稿#{user.posts.count}件", user_path(user) %>
            <a href="<%= following_user_path(user) %>">
              <strong id="following" class="stat">
                <%= user.following.count %>
              </strong>
              人をフォロー中
            </a>
            <a href="<%= followers_user_path(user) %>">
              フォロワー
              <strong id="followers" class="stat">
                <%= user.followers.count %>
              </strong>
              人
            </a>
          </p>  
          <%= user.introduce %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= will_paginate %>