config/routes.rb
Rails.application.routes.draw do
  
  root                              "top_pages#home"
  get    "/signup",             to: "users#new"
  post   "/signup",             to: "users#create"
  get    "/login",              to: "sessions#new"
  post   "/login",              to: "sessions#create"
  delete "/logout",             to: "sessions#destroy"
  
  resources :users, shallow: true, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
    resources :posts,         only: [:show, :new, :create, :destroy] do
      resources :comments,    only: [:create, :destroy]
    end
  end

  resources :password_resets, only: [:edit, :update]
  resources :relationships,   only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  validates :comment, length: { maximum: 140 }
  validates :image, presence: true
  validate  :image_size
  
  private
  
    # アップロードされた画像のサイズをバリデーションする
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "投稿できるサイズは5MB以下です。")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def index
    @post = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
  
  def new
    @post = Post.new
  end

  def create
    @user = params[:user_id]
    @post = current_user.posts.build(post_params)
    if @post.save
      flash.now[:success] = "投稿しました！"
      redirect_to  post_url(@post)
    else
      flash.now[:danger] = "画像が選択されていません。"
      render "new"
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:success] = "投稿を削除しました！"
    redirect_to user_path(current_user)
  end
  
  private
  
    def post_params
      params.require(:post).permit(:comment, :image)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<% provide(:title, "トップ") %>

<div class="container">
  <div class="row timeline">
    <div class="col-sm-8 col-sm-offset-2 col-xs-12 comment-box">
      <%= link_to image_tag(post.user.image, class: "img-responsive", size: 8*8,), user_path(post.user) %>
      <h1><%= link_to post.user.name, user_path(post.user) %></h1>
      <h4><%= post.created_at %>></h4>
    </div>
    <div class="col-sm-8 col-sm-offset-2 col-xs-12" id="image-show">
      <%= link_to image_tag(post.image, class: "img-responsive", size: 30*30), post_path(post)%>
    </div>
    <div class="col-sm-8 col-sm-offset-2 col-xs-12 comment-box">
      <% if post.comments.present? %>
        <% post.comments.each do |comment| %>
        <p>
          <%= comment.created_at %>
          <%= link_to comment.user.name,  user_path(comment.user) %>
          <%= comment.content %>
          <% if current_user.name == comment.user.name %>
            <%= link_to "コメントを削除", comment_path(comment), method: :delete,
                                                                  data: { confirm: "削除しますか？" } %>
          <% end %>
        </p>  
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="post-box">
        <h1>ラーメン画像を投稿する！！</h1>
        <%= form_for(@post, url: user_posts_path) do |f| %>
          <%= f.text_area :comment, placeholder: "コメント", style: "width: 300px;" %>
          <%= f.file_field :image, accept: 'image/jpeg,image/png', class: "file_select", style: "margin-top: 10px;" %>
          <p><%= f.submit "投稿する", class: "btn btn-primary", style: "margin-top: 20px;" %></p>
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "画像個別ページ") %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-12 comment-box">
      <%= link_to image_tag(@post.user.image, class: "img-responsive", size: 8*8,), user_path(@post.user) %>
      <h1><%= link_to @post.user.name, user_path(@post.user) %></h1>
      <h4><%= @post.created_at %>></h4>
    </div>
    <div class="col-sm-8 col-sm-offset-2 col-xs-12" id="image-show">
      <%= image_tag(@post.image, class: "img-responsive", size: 30*30)%>
    </div>
    <div class="col-sm-8 col-sm-offset-2 col-xs-12 comment-box">
      <% if @comments.present? %>
        <% @comments.each do |comment| %>
        <p>
          <%= comment.created_at %>
          <%= link_to comment.user.name,  user_path(comment.user) %>
          <%= comment.content %>
          <% if current_user?(comment.user) %>
            <%= link_to "コメントを削除", comment_path(comment), method: :delete,
                                          data: { confirm: "削除しますか？" } %>
          <% end %>
        </p>  
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-8 col-sm-offset-2 col-xs-12 comment-box">
      <% if logged_in? %>
        <%= form_for(@comment, url: post_comments_path(@post)) do |f| %>
          <%= f.text_field :content, placeholder: "コメントする" %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :post_id, :value => @post.id %>
          <p><%= f.submit "投稿する", class: "btn btn-primary" %></p>
        <% end %> 
      <% end %>
    </div>
    <div class="col-sm-8 col-sm-offset-2 col-xs-12 comment-box">
      <%= @post.comment %>
      <% if current_user?(@post.user) %>
      <%= link_to "投稿を削除", post_path(@post), method: :delete,
                                data: { confirm: "削除しますか？" } %>
      <% end %> 
    </div>
  </div>
</div>