config/routes.rb
Rails.application.routes.draw do
  
  root                              "top_pages#home"
  get    "/signup",             to: "users#new"
  post   "/signup",             to: "users#create"
  get    "/login",              to: "sessions#new"
  post   "/login",              to: "sessions#create"
  delete "/logout",             to: "sessions#destroy"
  
  resources :users, shallow: true, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
    resources :posts,         only: [:show, :new, :create, :destroy] do
      resources :comments,    only: [:create, :destroy]
    end
  end

  resources :password_resets, only: [:edit, :update]
  resources :relationships,   only: [:create, :destroy]
end

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= render 'layouts/rails_default' %>
<%= render 'layouts/shim' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #fff;">
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-1 col-xs-3 col-md-offset-1 col-md-3">
        <div class="navbar-header">
          <%= link_to "Rastagram", root_path, id: "logo", class: "navbar-brand" %>
        </div>
      </div>
      <div class="col-xs-offset-6 col-xs-2 col-md-offset-1 col-md-6">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to new_user_post_path(current_user) do %>
              <i class="fas fa-upload fa-2x"></i>
            <% end %>
          </li>  
          <li>
            <%= link_to logout_path, method: :delete, data: { confirm: "ログアウトしますか？" } do %>
              <i class="fas fa-sign-out-alt fa-2x"></i>
            <% end %>  
          </li>
          <li>
            <%= link_to current_user do %>
              <i class="fa fa-user fa-2x"></i>
            <% end %>  
          </li>
        </ul>
      </div>
    </div>  
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <% if logged_in? %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <div><%= debug(params) if Rails.env.development? %></div>
  </body>
</html>